### ISSUE TITLE
Add your custom social header

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Social-media-header#5]
Using the template provided, create your own social header and add to the README.md file with your name.

**Comment by sahupratik30** [comment]
Hi! I am really interested in solving this issue. Can you assign it to me?

**Comment by Evavic44** [comment]
> 
> 
> Hi! I am really interested in solving this issue. Can you assign it to me?

Sure, I plan on making this an open source project anyway where lots of persons will customize their profile with it.

**Comment by sahupratik30** [comment]
> > Hi! I am really interested in solving this issue. Can you assign it to me?
> 
> Sure, I plan on making this an open source project anyway where lots of persons will customize their profile with it.



> > Hi! I am really interested in solving this issue. Can you assign it to me?
> 
> Sure, I plan on making this an open source project anyway where lots of persons will customize their profile with it.

**Comment by sahupratik30** [comment]
Thanks
