### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Social-media-header#7]
For contributions,, add a pull request template contributors will follow to customize their social media header.

**Comment by itsmedeepak** [comment]
Please assign me this issue.

**Comment by Evavic44** [comment]
> Please assign me this issue.

Do you have a sample template I can see?

**Comment by itsmedeepak** [comment]
Which type of template you wanted to see?

**Comment by Evavic44** [comment]
> Which type of template you wanted to see?
> 

Or better still, go ahead. Will review your PR.

**Comment by itsmedeepak** [comment]
![itmedeepak](https://user-images.githubusercontent.com/74102432/122035369-07b3c880-cdf0-11eb-9572-0dee588c32c8.png)
 
Hey !!
please review it.

**Comment by Evavic44** [comment]
Lol, actually I meant a PR template. If you want to add your customized social media header, link your PR to this issue. #5 
P.S this is so cool. Love your design. ❤️ Also where did you get the neon colored GitHub logo.

**Comment by Evavic44** [comment]
> 
> 
> hey!!
> I'm begginer at github, Dont know how to contribute. Can you guide me??.
> if you like this logo please download it https://github.com/Evavic44/Social-media-header/files/6661110/github_neon.zip

If you already know the basics of Git & GitHub, here is a short simple step you can follow to contribute to this project [Link](https://github.com/Evavic44/Social-media-header#getting-started) If not, let me know. 💯

**Comment by itsmedeepak** [comment]
Let me try.
